name: Feature Reviewer Assignment and Approval Check

on:
    pull_request:
        types: [opened, synchronize]
    pull_request_review:
        types: [submitted]

env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
    HTML_URL: ${{ github.event.pull_request.html_url }}

jobs:
    assign-reviewers:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install dependencies
              run: npm ci

            - name: Print the directory
              run: cd .github/scripts && ls -la

            - name: Install modules
              run: npm i @octokit/rest

            - name: Assign reviewers
              if: github.event_name == 'pull_request'
              run: node ./.github/scripts/assign-reviewers.mjs

    # check-approvals:
    #     needs: assign-reviewers
    #     runs-on: ubuntu-latest
    #     steps:
    #         - name: Checkout code
    #             uses: actions/checkout@v2

    #         - name: Install dependencies
    #             run: npm ci

    #         - name: Check approvals
    #             if: github.event_name == 'pull_request_review'
    #             run: node .github/scripts/check-approvals.js
    #             env:
    #                 GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}